In [1]:
import pandas as pd

df = pd.read_excel('sales_raw_500.xlsx')

In [2]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 482 entries, 0 to 499
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    482 non-null    int64
 1   Order_Date  482 non-null    datetime64[ns]
 2   Customer    482 non-null    object
 3   Region      482 non-null    object
 4   Product     482 non-null    object
 5   Sales       482 non-null    int64
 6   Cost        482 non-null    int64
 7   Profit      482 non-null    int64
 8   Year        482 non-null    int32
 9   Month       482 non-null    int32
dtypes: datetime64[ns](1), int32(2), int64(4), object(3)
memory usage: 37.7+ KB

In [14]:
df.describe()

          Order_ID                     Order_Date         Sales          Cost        Profit         Year       Month
count   482.000000                            482    482.000000    482.000000    482.000000   482.000000  482.000000
mean   1252.205394  2023-08-20 04:07:58.008299008  41098.827801  30741.661826  10357.165975  2023.201245    5.711618
min    1001.000000            2023-01-04 00:00:00   5205.000000   3272.000000    677.000000  2023.000000    1.000000
25%    1127.250000            2023-05-03 00:00:00  22133.750000  16496.250000   5016.750000  2023.000000    3.000000
50%    1255.500000            2023-08-18 00:00:00  40984.000000  30396.000000   8290.000000  2023.000000    5.000000
75%    1376.750000            2023-12-13 18:00:00  58873.500000  43335.750000  14967.000000  2023.000000    9.000000
max    1500.000000            2024-03-26 00:00:00  79928.000000  71417.000000  30198.000000  2024.000000   12.000000
std     144.415782                            NaN  21555.310917  16571.560210   6911.859902     0.401347    3.542118

In [5]:
# Removes Duplicates 
df = df.drop_duplicates()

In [6]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [7]:
# Fix date columns

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce')

C:\Users\rajbh\AppData\Local\Temp\ipykernel_1964\317134078.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors = 'coerce')

In [9]:
# Drop NA or blank values from Order_date column

df = df.dropna(subset=['Order_Date'])

In [10]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [11]:
# Add new Column

df['Profit'] = df['Sales']-df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

C:\Users\rajbh\AppData\Local\Temp\ipykernel_1964\2145958943.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit'] = df['Sales']-df['Cost']
C:\Users\rajbh\AppData\Local\Temp\ipykernel_1964\2145958943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Order_Date'].dt.year
C:\Users\rajbh\AppData\Local\Temp\ipykernel_1964\2145958943.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['Order_Date'].dt.month

In [12]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost  Profit  Year  Month
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118    4171  2023      1
1        1002 2023-10-07     Aman   West   Laptop   8905   5593    3312  2023     10
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959   20028  2023     11
3        1004 2024-02-19    Rahul  South  Printer  49597  33892   15705  2024      2
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468   20329  2024      1
..        ...        ...      ...    ...      ...    ...    ...     ...   ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931    5778  2023     10
495      1496 2023-04-24    Kiran  North  Printer  23434  16388    7046  2023      4
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970   13037  2023      6
497      1498 2023-05-08     Aman   East   Tablet  19160  15636    3524  2023      5
499      1500 2023-10-07    Vikas  North  Printer  34567  22426   12141  2023     10

[482 rows x 10 columns]

In [18]:
df.to_csv('sales_cleaned_data.csv' ,index = False)

#### Connecting Python script to PostgreSQL

In [23]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\rajbh\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\rajbh\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rajbh\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 6.0 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.8 MB 5.0 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 5.0 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [24]:
# Engine build connection between python and sql

import pandas as pd
from sqlalchemy import create_engine

In [25]:
df = pd.read_csv('sales_cleaned_data.csv')

In [26]:
df

     Order_ID  Order_Date Customer Region  Product  Sales   Cost  Profit  Year  Month
0        1001  2023-01-13    Rohit  South   Mobile  23289  19118    4171  2023      1
1        1002  2023-10-07     Aman   West   Laptop   8905   5593    3312  2023     10
2        1003  2023-11-05    Rahul  South  Monitor  59987  39959   20028  2023     11
3        1004  2024-02-19    Rahul  South  Printer  49597  33892   15705  2024      2
4        1005  2024-01-26   Anjali  North   Laptop  54797  34468   20329  2024      1
..        ...         ...      ...    ...      ...    ...    ...     ...   ...    ...
477      1495  2023-10-18    Rahul  South  Monitor  46709  40931    5778  2023     10
478      1496  2023-04-24    Kiran  North  Printer  23434  16388    7046  2023      4
479      1497  2023-06-27   Anjali  South   Laptop  49007  35970   13037  2023      6
480      1498  2023-05-08     Aman   East   Tablet  19160  15636    3524  2023      5
481      1500  2023-10-07    Vikas  North  Printer  34567  22426   12141  2023     10

[482 rows x 10 columns]

In [35]:
# Data build connection inside engine so,build ecreate_engine

engine = create_engine('postgresql+psycopg2://postgres:123456@localhost:5432/Sales_db')
print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/Sales_db)

In [36]:
df.to_sql(name='sales_data', con=engine, if_exists='replace', index=False)

482